<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit7e3ea7e6bd41313be6a5e2082ed2b91d
{
    public static $prefixLengthsPsr4 = array (
        'I' => 
        array (
            'InstrumentalDisplay\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'InstrumentalDisplay\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit7e3ea7e6bd41313be6a5e2082ed2b91d::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit7e3ea7e6bd41313be6a5e2082ed2b91d::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit7e3ea7e6bd41313be6a5e2082ed2b91d::$classMap;

        }, null, ClassLoader::class);
    }
}
